#!/bin/bash

cd $(dirname "$0")

if [ -f usePDBs.txt ]
then
  rm usePDBs.txt
fi
if [ -f orig-1Dom.gdl ]
then
  rm orig-1Dom.gdl
fi
if [ -f abstract0-1Dom.gdl ]
then
  rm abstract0-1Dom.gdl
fi
if [ -f orig-1Prob.gdl ]
then
  rm orig-1Prob.gdl
fi
if [ -f abstract0-1Prob.gdl ]
then
  rm abstract0-1Prob.gdl
fi
if [ -f orig-1Part.gdl ]
then
  rm orig-1Part.gdl
fi
if [ -f abstract0-1Part.gdl ]
then
  rm abstract0-1Part.gdl
fi
if [ -f orig-1nPar.gdl ]
then
  rm orig-1nPar.gdl
fi
if [ -f abstract0-1nPar.gdl ]
then
  rm abstract0-1nPar.gdl
fi
touch transition
for trans in `ls transition*`
do
  rm $trans
done
if [ -f init ]
then
  rm init
fi
if [ -f goal ]
then
  rm goal
fi
if [ -f nextReorderingLimit ]
then
  rm nextReorderingLimit
fi
if [ -f reorderingsRemaining ]
then
  rm reorderingsRemaining
fi
if [ -f totalReordTime ]
then
    rm totalReordTime
fi
if [ -f lastReorderingTime ]
then
    rm lastReorderingTime
fi
if [ -f lastTotalTime ]
then
    rm lastTotalTime
fi
if [ -f variableOrdering ]
then
  rm variableOrdering
fi
if [ -f variableOrdering.txt ]
then
  rm variableOrdering.txt
fi
if [ -f statistics ]
then
  rm statistics
fi
noPDBs=0
while [ 1 ]
do
  if [ -f "abstract0-1PDB_"$noPDBs ]
  then
    rm "abstract0-1PDB_"$noPDBs
    ((noPDBs += 1))
  else
    break
  fi
done
if [ -d "dijkstraSteps" ]
then
  rm -rf dijkstraSteps
fi
