/* Generated By:JavaCC: Do not edit this line. GroundedPDDLParserConstants.java */
package pddl2bdd.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GroundedPDDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEFINE_TOK = 5;
  /** RegularExpression Id. */
  int DOMAIN_TOK = 6;
  /** RegularExpression Id. */
  int REQUIRE_TOK = 7;
  /** RegularExpression Id. */
  int PREDS_TOK = 8;
  /** RegularExpression Id. */
  int FUNC_TOK = 9;
  /** RegularExpression Id. */
  int ACTION_TOK = 10;
  /** RegularExpression Id. */
  int PARAM_TOK = 11;
  /** RegularExpression Id. */
  int PREC_TOK = 12;
  /** RegularExpression Id. */
  int EFF_TOK = 13;
  /** RegularExpression Id. */
  int OR_TOK = 14;
  /** RegularExpression Id. */
  int AND_TOK = 15;
  /** RegularExpression Id. */
  int NOT_TOK = 16;
  /** RegularExpression Id. */
  int INC_TOK = 17;
  /** RegularExpression Id. */
  int WHEN_TOK = 18;
  /** RegularExpression Id. */
  int PROBLEM_TOK = 19;
  /** RegularExpression Id. */
  int DOMAIN_TEST_TOK = 20;
  /** RegularExpression Id. */
  int INIT_TOK = 21;
  /** RegularExpression Id. */
  int GOAL_TOK = 22;
  /** RegularExpression Id. */
  int NAME = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DEFINE_TOK>",
    "<DOMAIN_TOK>",
    "<REQUIRE_TOK>",
    "<PREDS_TOK>",
    "<FUNC_TOK>",
    "<ACTION_TOK>",
    "\":parameters \"",
    "\":precondition \"",
    "\":effect \"",
    "<OR_TOK>",
    "<AND_TOK>",
    "<NOT_TOK>",
    "<INC_TOK>",
    "<WHEN_TOK>",
    "<PROBLEM_TOK>",
    "<DOMAIN_TEST_TOK>",
    "<INIT_TOK>",
    "<GOAL_TOK>",
    "<NAME>",
    "<NUMBER>",
    "\")\"",
    "\":\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
  };

}
