Document: gamer
Title: Debian gamer Manual
Author: <insert document author here>
Abstract: This manual describes what gamer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gamer/gamer.sgml.gz

Format: postscript
Files: /usr/share/doc/gamer/gamer.ps.gz

Format: text
Files: /usr/share/doc/gamer/gamer.text.gz

Format: HTML
Index: /usr/share/doc/gamer/html/index.html
Files: /usr/share/doc/gamer/html/*.html
